/*
 * Created on 18 Oct 2015 ( Time 18:29:34 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.sig.team.webworks.ekirana.crud.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "access_role_tokens"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="access_role_tokens")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="AccessRoleTokens.countAll", query="SELECT COUNT(x) FROM AccessRoleTokens x" )
} )
public class AccessRoleTokens implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="Role_Token_Id", nullable=false)
    private Integer    roleTokenId  ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="RoleId", nullable=false)
    private Integer    roleid       ;

    @Column(name="TokenId", nullable=false)
    private Integer    tokenid      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AccessRoleTokens()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setRoleTokenId( Integer roleTokenId )
    {
        this.roleTokenId = roleTokenId ;
    }
    public Integer getRoleTokenId()
    {
        return this.roleTokenId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : RoleId ( INT ) 
    public void setRoleid( Integer roleid )
    {
        this.roleid = roleid;
    }
    public Integer getRoleid()
    {
        return this.roleid;
    }

    //--- DATABASE MAPPING : TokenId ( INT ) 
    public void setTokenid( Integer tokenid )
    {
        this.tokenid = tokenid;
    }
    public Integer getTokenid()
    {
        return this.tokenid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(roleTokenId);
        sb.append("]:"); 
        sb.append(roleid);
        sb.append("|");
        sb.append(tokenid);
        return sb.toString(); 
    } 

}