/*
 * Created on 18 Oct 2015 ( Time 18:29:34 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.sig.team.webworks.ekirana.crud.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "access_tokens"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="access_tokens")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="AccessTokens.countAll", query="SELECT COUNT(x) FROM AccessTokens x" )
} )
public class AccessTokens implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="TokenId", nullable=false)
    private Integer    tokenid      ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="TokenName", nullable=false, length=100)
    private String     tokenname    ;

    @Column(name="Description", nullable=false, length=100)
    private String     description  ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AccessTokens()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setTokenid( Integer tokenid )
    {
        this.tokenid = tokenid ;
    }
    public Integer getTokenid()
    {
        return this.tokenid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : TokenName ( VARCHAR ) 
    public void setTokenname( String tokenname )
    {
        this.tokenname = tokenname;
    }
    public String getTokenname()
    {
        return this.tokenname;
    }

    //--- DATABASE MAPPING : Description ( VARCHAR ) 
    public void setDescription( String description )
    {
        this.description = description;
    }
    public String getDescription()
    {
        return this.description;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(tokenid);
        sb.append("]:"); 
        sb.append(tokenname);
        sb.append("|");
        sb.append(description);
        return sb.toString(); 
    } 

}