/*
 * Created on 18 Oct 2015 ( Time 18:29:34 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.sig.team.webworks.ekirana.crud.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "access_roles"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="access_roles")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="AccessRoles.countAll", query="SELECT COUNT(x) FROM AccessRoles x" )
} )
public class AccessRoles implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="RoleId", nullable=false)
    private Integer    roleid       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="RoleName", nullable=false, length=100)
    private String     rolename     ;

    @Column(name="Description", nullable=false, length=100)
    private String     description  ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AccessRoles()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setRoleid( Integer roleid )
    {
        this.roleid = roleid ;
    }
    public Integer getRoleid()
    {
        return this.roleid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : RoleName ( VARCHAR ) 
    public void setRolename( String rolename )
    {
        this.rolename = rolename;
    }
    public String getRolename()
    {
        return this.rolename;
    }

    //--- DATABASE MAPPING : Description ( VARCHAR ) 
    public void setDescription( String description )
    {
        this.description = description;
    }
    public String getDescription()
    {
        return this.description;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(roleid);
        sb.append("]:"); 
        sb.append(rolename);
        sb.append("|");
        sb.append(description);
        return sb.toString(); 
    } 

}