/*
 * Created on 18 Oct 2015 ( Time 18:29:34 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.sig.team.webworks.ekirana.crud.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "access_user"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="access_user")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="AccessUser.countAll", query="SELECT COUNT(x) FROM AccessUser x" )
} )
public class AccessUser implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="UserId", nullable=false)
    private Integer    userid       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="RoleId", nullable=false)
    private Integer    roleid       ;

    @Column(name="PartnerId", nullable=false)
    private Integer    partnerid    ;

    @Column(name="FullName", nullable=false, length=100)
    private String     fullname     ;

    @Column(name="UserName", nullable=false, length=100)
    private String     username     ;

    @Column(name="Password", length=255)
    private String     password     ;

    @Temporal(TemporalType.DATE)
    @Column(name="ValidAfter")
    private Date       validafter   ;

    @Temporal(TemporalType.DATE)
    @Column(name="ValidBefore")
    private Date       validbefore  ;

    @Column(name="Failed_Logins_Count", nullable=false)
    private Integer    failedLoginsCount ;

    @Column(name="AccessKey", length=100)
    private String     accesskey    ;

    @Column(name="AgreementId")
    private Integer    agreementid  ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AccessUser()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUserid( Integer userid )
    {
        this.userid = userid ;
    }
    public Integer getUserid()
    {
        return this.userid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : RoleId ( INT ) 
    public void setRoleid( Integer roleid )
    {
        this.roleid = roleid;
    }
    public Integer getRoleid()
    {
        return this.roleid;
    }

    //--- DATABASE MAPPING : PartnerId ( INT ) 
    public void setPartnerid( Integer partnerid )
    {
        this.partnerid = partnerid;
    }
    public Integer getPartnerid()
    {
        return this.partnerid;
    }

    //--- DATABASE MAPPING : FullName ( VARCHAR ) 
    public void setFullname( String fullname )
    {
        this.fullname = fullname;
    }
    public String getFullname()
    {
        return this.fullname;
    }

    //--- DATABASE MAPPING : UserName ( VARCHAR ) 
    public void setUsername( String username )
    {
        this.username = username;
    }
    public String getUsername()
    {
        return this.username;
    }

    //--- DATABASE MAPPING : Password ( VARCHAR ) 
    public void setPassword( String password )
    {
        this.password = password;
    }
    public String getPassword()
    {
        return this.password;
    }

    //--- DATABASE MAPPING : ValidAfter ( DATE ) 
    public void setValidafter( Date validafter )
    {
        this.validafter = validafter;
    }
    public Date getValidafter()
    {
        return this.validafter;
    }

    //--- DATABASE MAPPING : ValidBefore ( DATE ) 
    public void setValidbefore( Date validbefore )
    {
        this.validbefore = validbefore;
    }
    public Date getValidbefore()
    {
        return this.validbefore;
    }

    //--- DATABASE MAPPING : Failed_Logins_Count ( INT ) 
    public void setFailedLoginsCount( Integer failedLoginsCount )
    {
        this.failedLoginsCount = failedLoginsCount;
    }
    public Integer getFailedLoginsCount()
    {
        return this.failedLoginsCount;
    }

    //--- DATABASE MAPPING : AccessKey ( VARCHAR ) 
    public void setAccesskey( String accesskey )
    {
        this.accesskey = accesskey;
    }
    public String getAccesskey()
    {
        return this.accesskey;
    }

    //--- DATABASE MAPPING : AgreementId ( INT ) 
    public void setAgreementid( Integer agreementid )
    {
        this.agreementid = agreementid;
    }
    public Integer getAgreementid()
    {
        return this.agreementid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(userid);
        sb.append("]:"); 
        sb.append(roleid);
        sb.append("|");
        sb.append(partnerid);
        sb.append("|");
        sb.append(fullname);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(validafter);
        sb.append("|");
        sb.append(validbefore);
        sb.append("|");
        sb.append(failedLoginsCount);
        sb.append("|");
        sb.append(accesskey);
        sb.append("|");
        sb.append(agreementid);
        return sb.toString(); 
    } 

}