/*
 * Created on 18 Oct 2015 ( Time 18:29:34 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.sig.team.webworks.ekirana.crud.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "brand"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="brand")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Brand.countAll", query="SELECT COUNT(x) FROM Brand x" )
} )
public class Brand implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="brandId", nullable=false)
    private Integer    brandid      ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="brandName", nullable=false, length=255)
    private String     brandname    ;

    @Column(name="description", length=999)
    private String     description  ;

    @Column(name="modeInfo", length=999)
    private String     modeinfo     ;

    @Column(name="url", length=999)
    private String     url          ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdOn")
    private Date       createdon    ;

    @Column(name="createdBy", length=9999)
    private String     createdby    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updatedOn", nullable=false)
    private Date       updatedon    ;

    @Column(name="updatedBy", length=9999)
    private String     updatedby    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Brand()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setBrandid( Integer brandid )
    {
        this.brandid = brandid ;
    }
    public Integer getBrandid()
    {
        return this.brandid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : brandName ( VARCHAR ) 
    public void setBrandname( String brandname )
    {
        this.brandname = brandname;
    }
    public String getBrandname()
    {
        return this.brandname;
    }

    //--- DATABASE MAPPING : description ( VARCHAR ) 
    public void setDescription( String description )
    {
        this.description = description;
    }
    public String getDescription()
    {
        return this.description;
    }

    //--- DATABASE MAPPING : modeInfo ( VARCHAR ) 
    public void setModeinfo( String modeinfo )
    {
        this.modeinfo = modeinfo;
    }
    public String getModeinfo()
    {
        return this.modeinfo;
    }

    //--- DATABASE MAPPING : url ( VARCHAR ) 
    public void setUrl( String url )
    {
        this.url = url;
    }
    public String getUrl()
    {
        return this.url;
    }

    //--- DATABASE MAPPING : createdOn ( TIMESTAMP ) 
    public void setCreatedon( Date createdon )
    {
        this.createdon = createdon;
    }
    public Date getCreatedon()
    {
        return this.createdon;
    }

    //--- DATABASE MAPPING : createdBy ( VARCHAR ) 
    public void setCreatedby( String createdby )
    {
        this.createdby = createdby;
    }
    public String getCreatedby()
    {
        return this.createdby;
    }

    //--- DATABASE MAPPING : updatedOn ( TIMESTAMP ) 
    public void setUpdatedon( Date updatedon )
    {
        this.updatedon = updatedon;
    }
    public Date getUpdatedon()
    {
        return this.updatedon;
    }

    //--- DATABASE MAPPING : updatedBy ( VARCHAR ) 
    public void setUpdatedby( String updatedby )
    {
        this.updatedby = updatedby;
    }
    public String getUpdatedby()
    {
        return this.updatedby;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(brandid);
        sb.append("]:"); 
        sb.append(brandname);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(modeinfo);
        sb.append("|");
        sb.append(url);
        sb.append("|");
        sb.append(createdon);
        sb.append("|");
        sb.append(createdby);
        sb.append("|");
        sb.append(updatedon);
        sb.append("|");
        sb.append(updatedby);
        return sb.toString(); 
    } 

}