/*
 * Created on 18 Oct 2015 ( Time 18:29:34 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.sig.team.webworks.ekirana.crud.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

import org.codehaus.jackson.annotate.JsonIgnore;
/**
 * Persistent class for entity stored in table "image"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="image")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Image.countAll", query="SELECT COUNT(x) FROM Image x" )
} )
public class Image implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", length=999)
    private String     name         ;

    @Column(name="path", length=999)
    private String     path         ;

    @Lob
    @Column(name="imageData")
    @JsonIgnore
    private byte[]     imagedata    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Image()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : path ( VARCHAR ) 
    public void setPath( String path )
    {
        this.path = path;
    }
    public String getPath()
    {
        return this.path;
    }

    //--- DATABASE MAPPING : imageData ( LONGBLOB ) 
    public void setImagedata( byte[] imagedata )
    {
        this.imagedata = imagedata;
    }
    public byte[] getImagedata()
    {
        return this.imagedata;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(path);
        // attribute 'imagedata' not usable (type = byte[])
        return sb.toString(); 
    } 

}