/*
 * Created on 18 Oct 2015 ( Time 18:29:34 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.sig.team.webworks.ekirana.crud.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "item_offers"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="item_offers")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ItemOffers.countAll", query="SELECT COUNT(x) FROM ItemOffers x" )
} )
public class ItemOffers implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="itemId")
    private Integer    itemid       ;

    @Column(name="discountInPerentage")
    private Float      discountinperentage ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createOn", nullable=false)
    private Date       createon     ;

    @Column(name="createBy", length=999)
    private String     createby     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updatedOn", nullable=false)
    private Date       updatedon    ;

    @Column(name="updateBy", length=999)
    private String     updateby     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ItemOffers()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : itemId ( INT ) 
    public void setItemid( Integer itemid )
    {
        this.itemid = itemid;
    }
    public Integer getItemid()
    {
        return this.itemid;
    }

    //--- DATABASE MAPPING : discountInPerentage ( FLOAT ) 
    public void setDiscountinperentage( Float discountinperentage )
    {
        this.discountinperentage = discountinperentage;
    }
    public Float getDiscountinperentage()
    {
        return this.discountinperentage;
    }

    //--- DATABASE MAPPING : createOn ( TIMESTAMP ) 
    public void setCreateon( Date createon )
    {
        this.createon = createon;
    }
    public Date getCreateon()
    {
        return this.createon;
    }

    //--- DATABASE MAPPING : createBy ( VARCHAR ) 
    public void setCreateby( String createby )
    {
        this.createby = createby;
    }
    public String getCreateby()
    {
        return this.createby;
    }

    //--- DATABASE MAPPING : updatedOn ( TIMESTAMP ) 
    public void setUpdatedon( Date updatedon )
    {
        this.updatedon = updatedon;
    }
    public Date getUpdatedon()
    {
        return this.updatedon;
    }

    //--- DATABASE MAPPING : updateBy ( VARCHAR ) 
    public void setUpdateby( String updateby )
    {
        this.updateby = updateby;
    }
    public String getUpdateby()
    {
        return this.updateby;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(itemid);
        sb.append("|");
        sb.append(discountinperentage);
        sb.append("|");
        sb.append(createon);
        sb.append("|");
        sb.append(createby);
        sb.append("|");
        sb.append(updatedon);
        sb.append("|");
        sb.append(updateby);
        return sb.toString(); 
    } 

}