/*
 * Created on 18 Oct 2015 ( Time 18:29:35 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.sig.team.webworks.ekirana.crud.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "order_payment"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="order_payment")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="OrderPayment.countAll", query="SELECT COUNT(x) FROM OrderPayment x" )
} )
public class OrderPayment implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="orderId")
    private Integer    orderid      ;

    @Column(name="totalPaymentMade")
    private Float      totalpaymentmade ;

    @Column(name="paymentMode")
    private Integer    paymentmode  ;

    @Column(name="paymentStatus")
    private Integer    paymentstatus ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdOn")
    private Date       createdon    ;

    @Column(name="createdBy", length=9999)
    private String     createdby    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updatedOn", nullable=false)
    private Date       updatedon    ;

    @Column(name="updatedBy", length=9999)
    private String     updatedby    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public OrderPayment()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : orderId ( INT ) 
    public void setOrderid( Integer orderid )
    {
        this.orderid = orderid;
    }
    public Integer getOrderid()
    {
        return this.orderid;
    }

    //--- DATABASE MAPPING : totalPaymentMade ( FLOAT ) 
    public void setTotalpaymentmade( Float totalpaymentmade )
    {
        this.totalpaymentmade = totalpaymentmade;
    }
    public Float getTotalpaymentmade()
    {
        return this.totalpaymentmade;
    }

    //--- DATABASE MAPPING : paymentMode ( INT ) 
    public void setPaymentmode( Integer paymentmode )
    {
        this.paymentmode = paymentmode;
    }
    public Integer getPaymentmode()
    {
        return this.paymentmode;
    }

    //--- DATABASE MAPPING : paymentStatus ( INT ) 
    public void setPaymentstatus( Integer paymentstatus )
    {
        this.paymentstatus = paymentstatus;
    }
    public Integer getPaymentstatus()
    {
        return this.paymentstatus;
    }

    //--- DATABASE MAPPING : createdOn ( TIMESTAMP ) 
    public void setCreatedon( Date createdon )
    {
        this.createdon = createdon;
    }
    public Date getCreatedon()
    {
        return this.createdon;
    }

    //--- DATABASE MAPPING : createdBy ( VARCHAR ) 
    public void setCreatedby( String createdby )
    {
        this.createdby = createdby;
    }
    public String getCreatedby()
    {
        return this.createdby;
    }

    //--- DATABASE MAPPING : updatedOn ( TIMESTAMP ) 
    public void setUpdatedon( Date updatedon )
    {
        this.updatedon = updatedon;
    }
    public Date getUpdatedon()
    {
        return this.updatedon;
    }

    //--- DATABASE MAPPING : updatedBy ( VARCHAR ) 
    public void setUpdatedby( String updatedby )
    {
        this.updatedby = updatedby;
    }
    public String getUpdatedby()
    {
        return this.updatedby;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(orderid);
        sb.append("|");
        sb.append(totalpaymentmade);
        sb.append("|");
        sb.append(paymentmode);
        sb.append("|");
        sb.append(paymentstatus);
        sb.append("|");
        sb.append(createdon);
        sb.append("|");
        sb.append(createdby);
        sb.append("|");
        sb.append(updatedon);
        sb.append("|");
        sb.append(updatedby);
        return sb.toString(); 
    } 

}